# Generated by Django 4.2.1 on 2023-06-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
    ]
